---
# This file is part of the NiAS project (https://github.com/nias-project).
# Copyright NiAS developers and contributors. All rights reserved.
# License: BSD 2-Clause License (https://opensource.org/licenses/BSD-2-Clause)
#
# Markdown linter rules
# linter rules doc: https://github.com/DavidAnson/markdownlint
MD003:
  style: atx  # use "#" for headers
MD013:
  line_length: 120  # line length 80 is far too short
MD033:
  allowed_elements: [img]  # allowed HTML tags
MD034: false  # allow bare URLs
MD040: false  # ``` fenced code must have language set
MD041: false  # require heading as first line in file
