---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  # We are staying with v16 at the moment to be in line with Visual Studio
  rev: v18.1.6
  hooks:
  - id: clang-format
    types_or: [c, c++]
    exclude: .github
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml>=5.1]     # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
    args: [-i, --config-files=.cmake_format.py]
    exclude: config.h.cmake
  - id: cmake-lint
    additional_dependencies: [pyyaml>=5.1]     # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
    args: [--config-files=.cmake_format.py]
    exclude: config.h.cmake
- repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
  rev: v0.1.3
  hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format
- repo: https://github.com/rhysd/actionlint
  # TODO: Use version number instead of commit hash once there is a release with
  # https://github.com/rhysd/actionlint/pull/425
  rev: 4c3740eb45958e125c91bfb19ee93053371454ec
  hooks:
  - id: actionlint
# this should go last since it will fix line endings broken by other tools
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    # The pre-commit check on CI detects some whitespace changes if we include .github
    exclude: .github
  - id: check-added-large-files
  - id: check-case-conflict
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-xml
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys, --indent=4]
    exclude: .*\.ipynb$
  - id: check-symlinks
  - id: debug-statements
  - id: fix-byte-order-marker
